---

# Ensure shared path exists
- name: ANSISTRANO | Ensure shared paths exists, default behaviour
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}/{{ symlink_properties }}"
  when:
    - symlink_properties.src is not defined
    - symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Block for handling the symlink's when extended definitions are given
  block:

   - assert:
       that:
         - symlink_properties.src is defined
         - symlink_properties.dest is defined

   - name: ANSISTRANO | Ensure shared paths exists, dest and src provided
     file:
       state: directory
       path: "{{ ansistrano_shared_path }}/{{ symlink_properties.src }}"

  when: symlink_properties.src is defined or symlink_properties.dest is defined
