---
# Setup folders
- name: ANSISTRANO | Ensure deployment base path exists
  file:
    state: directory
    path: "{{ ansistrano_deploy_to }}"

- name: ANSISTRANO | Ensure releases folder exists
  file:
    state: directory
    path: "{{ ansistrano_releases_path }}"

- name: ANSISTRANO | Ensure shared elements folder exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}"

- include: setup-shared-paths.yml
  vars:
    symlink_properties: "{{ item }}"
  with_items:
    - "{{ ansistrano_shared_paths }}"
  when: ansistrano_ensure_shared_paths_exist|bool

- name: ANSISTRANO | Ensure basedir shared files exists
  file:
    state: directory
    path: "{{ ansistrano_shared_path }}/{{ item | dirname }}"
  with_items: "{{ ansistrano_shared_files }}"
  when: ansistrano_ensure_basedirs_shared_files_exist|bool
