---

# Ensure symlinks target paths is absent
# This was removed in 1.7.3 to improve speed but it introduced regressions in cases where
# there are .gitkeep files in such folders (common practice in some PHP frameworks)
- name: ANSISTRANO | Ensure shared paths targets are absent, default behaviour
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties }}"
  when: symlink_properties.src is not defined and symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Create softlinks for shared paths and files, default behaviour
  file:
    state: link
    path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties }}"
    src: "{{ symlink_properties | regex_replace('[^\\/]+', '..') }}/../shared/{{ symlink_properties }}"
  when: symlink_properties.src is not defined and symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Block for handling the symlink's when extended definitions are given
  block:

   - assert:
       that:
         - symlink_properties.src is defined
         - symlink_properties.dest is defined

   - name: ANSISTRANO | Ensure shared paths targets are absent, src and dest specified
     file:
       state: absent
       path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties.src }}"

   - name: ANSISTRANO | Create softlinks for shared paths and files, src and dest specified
     file:
       state: link
       path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties.src }}"
       src: "{{ symlink_properties.src | regex_replace('[^\\/]+', '..') }}/../shared/{{ symlink_properties.dest }}"
  when: symlink_properties.src is defined or symlink_properties.dest is defined
