---


# Ensure symlinks target paths is absent
# This was removed in 1.7.3 to improve speed but it introduced regressions in cases where 
# there are .gitkeep files in such folders (common practice in some PHP frameworks)
- name: ANSISTRANO | Ensure shared paths targets are absent
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/{{ item }}"
  with_flattened:
    - "{{ ansistrano_shared_paths }}"
    - "{{ ansistrano_shared_files }}"

- include: symlink-shared-item.yml
  vars:
    symlink_properties: "{{ item }}"
  with_flattened:
    - "{{ ansistrano_shared_paths }}"
    - "{{ ansistrano_shared_files }}"

# Remove previous .rsync-filter file (rsync current deployment)
- name: ANSISTRANO | Ensure .rsync-filter is absent
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/.rsync-filter"
  when: ansistrano_current_via == "rsync"

- include: symlink-shared-item-rsync.yml
  vars:
    symlink_properties: "{{ item }}"
  with_flattened:
    - "{{ ansistrano_shared_paths }}"
    - "{{ ansistrano_shared_files }}"