---
# Symlinks shared paths and files
- name: ANSISTRANO | Create softlinks for shared paths and files, default behaviour
  file:
    state: link
    path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties }}"
    src: "{{ symlink_properties | regex_replace('[^\\/]+', '..') }}/../shared/{{ symlink_properties }}"
  when: symlink_properties.src is not defined and symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Block for handling the symlink's when extended definitions are given
  block:
   - assert:
     that:
       - symlink_properties.src is defined
       - symlink_properties.dest is defined

   - name: ANSISTRANO | Create softlinks for shared paths and files, src and dest specified
     file:
       state: link
       path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties.dest }}"
       src: "{{ symlink_properties.src | regex_replace('[^\\/]+', '..') }}/../shared/{{ symlink_properties.src }}"
  when: symlink_properties.src is defined or symlink_properties.dest is defined
