---
# Setup .rsync-filter file for current rsync deployment (exclude shared folders for rsync current deployment)
- name: ANSISTRANO | Setup .rsync-filter with shared-folders
  lineinfile:
    dest: "{{ ansistrano_release_path.stdout }}/.rsync-filter"
    line: "- /{{ symlink_properties }}"
    create: yes
  when: symlink_properties.src is not defined and symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Block for handling the .rsync-filter file when extended definitions are given
  block:


   - assert:
       that:
         - symlink_properties.src is defined
         - symlink_properties.dest is defined

    # Setup .rsync-filter file for current rsync deployment (exclude shared folders for rsync current deployment)
   - name: ANSISTRANO | Setup .rsync-filter with shared-folders
     lineinfile:
       dest: "{{ ansistrano_release_path.stdout }}/.rsync-filter"
       line: "- /{{ symlink_properties.src }}"
       create: yes

  when: symlink_properties.src is defined or symlink_properties.dest is defined
