---

- debug:
    var: symlink_properties

# Ensure symlinks target paths is absent
# This was removed in 1.7.3 to improve speed but it introduced regressions in cases where
# there are .gitkeep files in such folders (common practice in some PHP frameworks)
- name: ANSISTRANO | Ensure shared paths targets are absent, default behaviour
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties }}"
  when: symlink_properties.src is not defined and symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Create softlinks for shared paths and files, default behaviour
  file:
    state: link
    path: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties }}"
    src: "{{ ansistrano_shared_path }}/{{ symlink_properties }}"
  when: symlink_properties.src is not defined and symlink_properties.dest is not defined

# Symlinks shared paths and files
- name: ANSISTRANO | Block for handling the symlink's when extended definitions are given
  block:

   - assert:
       that:
         - symlink_properties.src is defined
         - symlink_properties.dest is defined

# tackle absolute symlinks gently
   - set_fact:
      symlink_dest: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties.dest }}"
     when: symlink_properties.dest[0] != "/"

   - set_fact:
      symlink_dest: "{{ symlink_properties.dest }}"
     when: symlink_properties.dest[0] == "/"

   - name: ANSISTRANO | Ensure shared paths targets are absent, src and dest specified
     file:
       state: absent
       path: "{{ symlink_dest }}"

   - name: ANSISTRANO | Create softlinks for shared paths and files, src and dest specified
     file:
       state: link
       src: "{{ ansistrano_shared_path }}/{{ symlink_properties.src }}"
       dest: "{{ symlink_dest }}"
     when: symlink_properties.force is not defined or not symlink_properties.force|bool

#   - name: ANSISTRANO | Create softlinks for shared paths and files, src and dest specified, forced
#     file:
#       state: link
#       src: "{{ ansistrano_release_path.stdout }}/shared/{{ symlink_properties.src }}"
#       dest: "{{ ansistrano_release_path.stdout }}/{{ symlink_properties.dest }}"
#       force: true
#     when: symlink_properties.force is defined and symlink_properties.force|bool

  when: symlink_properties.src is defined or symlink_properties.dest is defined
