---

- include: symlink-shared-item.yml
  vars:
    symlink_properties: "{{ item }}"
  with_flattened:
    - "{{ ansistrano_shared_paths }}"
    - "{{ ansistrano_shared_files }}"

# Remove previous .rsync-filter file (rsync current deployment)
- name: ANSISTRANO | Ensure .rsync-filter is absent
  file:
    state: absent
    path: "{{ ansistrano_release_path.stdout }}/.rsync-filter"
  when: ansistrano_current_via == "rsync"

- include: symlink-shared-item-rsync.yml
  vars:
    symlink_properties: "{{ item }}"
  with_flattened:
    - "{{ ansistrano_shared_paths }}"
    - "{{ ansistrano_shared_files }}"